In [1]:
import pandas as pd
from sqlalchemy import create_engine
from sqlalchemy.engine import URL

connection_url = URL.create(
    "postgresql+psycopg2",
    username="postgres",
    password="Shanks@123",
    host="localhost",
    port=5432,
    database="job_market_db"
)

engine = create_engine(connection_url)

jobs = pd.read_sql(
    """
    SELECT
        job_id,
        title,
        normalized_title,
        job_description,
        tags_and_skills
    FROM jobs
    """,
    engine
)

print("Jobs loaded:", len(jobs))

Jobs loaded: 97679

In [2]:
skills = [
    # Programming
    "Python", "Java", "JavaScript", "TypeScript", "C", "C++", "C#",
    "Go", "Golang", "Rust", "Kotlin", "Swift", "R", "Scala", "PHP",
    "Ruby", "MATLAB", "Dart", "Perl", "Shell", "Bash", "PowerShell",

    # Data / ML / AI
    "Machine Learning", "Deep Learning", "Artificial Intelligence",
    "Data Science", "Data Analytics", "Statistical Analysis",
    "Natural Language Processing", "NLP", "Computer Vision",
    "Generative AI", "Large Language Models", "LLM",
    "Reinforcement Learning", "Time Series", "Predictive Modeling",
    "Feature Engineering", "Model Deployment", "MLOps",

    # Python / ML libraries
    "Pandas", "NumPy", "SciPy", "Scikit-learn", "TensorFlow",
    "Keras", "PyTorch", "XGBoost", "LightGBM", "Matplotlib",
    "Seaborn", "Plotly", "NLTK", "spaCy", "OpenCV",
    "Hugging Face", "Transformers",

    # Databases / SQL
    "SQL", "PostgreSQL", "MySQL", "Oracle", "SQL Server",
    "SQLite", "MongoDB", "Redis", "Cassandra", "DynamoDB",
    "Elasticsearch", "Neo4j", "PL/SQL",

    # Big Data
    "Apache Spark", "PySpark", "Hadoop", "Hive", "HBase",
    "Kafka", "Apache Kafka", "Airflow", "Apache Airflow",
    "Flink", "Databricks", "Snowflake", "BigQuery",
    "Presto", "Trino",

    # Cloud
    "AWS", "Amazon Web Services", "Azure", "Microsoft Azure",
    "Google Cloud", "GCP", "Amazon EC2", "AWS EC2",
    "Amazon S3", "AWS S3", "AWS Lambda", "AWS RDS",
    "Azure Data Factory", "Azure Synapse", "Azure Blob Storage",
    "Google BigQuery",

    # DevOps
    "Docker", "Kubernetes", "Jenkins", "Git", "GitHub",
    "GitLab", "Bitbucket", "Terraform", "Ansible", "CI/CD",
    "GitHub Actions", "GitLab CI", "Azure DevOps",

    # Web / Backend
    "HTML", "CSS", "React", "Angular", "Vue.js", "Node.js",
    "Express.js", "Spring Boot", "Spring", "Django", "Flask",
    "FastAPI", "REST API", "RESTful API", "GraphQL",
    "Microservices", "API Development",

    # Java ecosystem
    "Maven", "Gradle", "Hibernate", "JPA", "JUnit",
    "Spring MVC", "Spring Security",

    # BI / Visualization
    "Power BI", "Tableau", "Looker", "Qlik", "Excel",
    "Advanced Excel", "VBA", "Power Query", "DAX",

    # Data Engineering
    "ETL", "ELT", "Data Engineering", "Data Pipeline",
    "Data Warehousing", "Data Warehouse", "Data Lake",
    "Data Modeling", "Data Integration", "Data Governance",
    "Data Quality",

    # ML Algorithms
    "Regression", "Linear Regression", "Logistic Regression",
    "Random Forest", "Gradient Boosting", "Decision Trees",
    "Support Vector Machine", "SVM", "KNN", "K-Means",
    "Clustering", "Classification", "Neural Networks",
    "CNN", "RNN", "LSTM", "Transformer", "BERT", "GPT",
    "Word2Vec", "Embeddings",

    # Software Engineering
    "Object Oriented Programming", "OOP", "Data Structures",
    "Algorithms", "System Design", "Software Development",
    "Software Engineering", "Agile", "Scrum", "Jira",
    "Confluence", "Unit Testing", "Integration Testing",
    "Test Automation", "Selenium",

    # Tools
    "Jupyter", "Jupyter Notebook", "VS Code", "Visual Studio",
    "IntelliJ IDEA", "Eclipse", "Postman", "Swagger",
    "Linux", "Unix",

    # Security
    "Cybersecurity", "Information Security", "Network Security",
    "Cloud Security", "IAM", "OAuth", "JWT", "SSL", "TLS",

    # Networking
    "TCP/IP", "HTTP", "DNS", "VPN", "Networking", "Cisco",

    # Enterprise
    "SAP", "Salesforce", "ServiceNow", "Oracle ERP",
    "SAP S/4HANA", "SAP ABAP",

    # General analytics
    "Data Visualization", "Data Cleaning", "Data Mining",
    "Business Intelligence", "Business Analytics",
    "Statistical Modeling", "Research", "Forecasting",
    "Optimization"
]

skills = sorted(set(skills), key=str.lower)

print("Taxonomy size:", len(skills))

Taxonomy size: 234

In [3]:
import spacy
from spacy.matcher import PhraseMatcher

nlp = spacy.blank("en")

matcher = PhraseMatcher(
    nlp.vocab,
    attr="LOWER"
)

patterns = [
    nlp.make_doc(skill)
    for skill in skills
]

matcher.add(
    "SKILLS",
    patterns
)

print("PhraseMatcher ready")

PhraseMatcher ready

In [5]:
tech_jobs = jobs[
    jobs["title"].str.contains(
        "data scientist|data analyst|machine learning|software engineer|developer|data engineer",
        case=False,
        na=False,
        regex=True
    )
]

print("Tech jobs found:", len(tech_jobs))

print(
    tech_jobs[
        ["job_id", "title"]
    ].head(10)
)

Tech jobs found: 12742
           job_id                                              title
27   260925914626  ATM Implementation - Software Engineer / Senio...
28   260925914625                   Software Engineer Implementation
36   260925504381           Embedded Software Engineering Specialist
54   260925503738                           Senior Software Engineer
57   260925503653                          Sr.Lead Software Engineer
69   260925502576                                      PHP Developer
88   260925502136                           Senior Software Engineer
117  260925032165                          Python Software Developer
140  260925026506           Software Developer (Mainframe Assembler)
143  260925025955                                Fullstack Developer

In [6]:
idx = tech_jobs.index[0]

text = jobs.loc[idx, "job_description"]

doc = nlp(text)

matches = matcher(doc)

found_skills = sorted(
    set(
        doc[start:end].text
        for _, start, end in matches
    ),
    key=str.lower
)

print("Job title:", jobs.loc[idx, "title"])
print("\nExtracted skills:")
print(found_skills)

Job title: ATM Implementation - Software Engineer / Senior Software Engineer

Extracted skills:
['Linux', 'MySQL']

In [7]:
print(text[:3000])

<p><strong>Experience</strong>: 4 - 8 Years of relevant experience working in the skillset</p><p><strong>Skillset:</strong></p><ul><li>Hands on experience on ATM/CRM/BNA System.</li><li>Should have knowledge on ATM terminals of NCR / Wincor / Okie / Hitachi makes</li><li>Extensive experience on XFS layer.</li><li>Understanding of client  server model.</li><li>Should have experience on Screen Design, Screen Flow, States, etc</li><li>Should have working experience on NDC/DDC Protocol.</li><li>Should have working experience with NDC/DDC protocol Setup.</li><li>Working knowledge on ISO / API Interfaces.</li><li>Experience on Terminal driving certifications like ADVT and MTIP.</li><li>Should have Working experience Linux and MySQL / MariaDB.</li><li>Batch Scripting will have added advantage</li></ul>

In [8]:
from bs4 import BeautifulSoup

def clean_html(text):
    if pd.isna(text):
        return ""

    return BeautifulSoup(
        str(text),
        "html.parser"
    ).get_text(" ", strip=True)

In [9]:
clean_text = clean_html(text)

print(clean_text[:2000])

Experience : 4 - 8 Years of relevant experience working in the skillset Skillset: Hands on experience on ATM/CRM/BNA System. Should have knowledge on ATM terminals of NCR / Wincor / Okie / Hitachi makes Extensive experience on XFS layer. Understanding of client  server model. Should have experience on Screen Design, Screen Flow, States, etc Should have working experience on NDC/DDC Protocol. Should have working experience with NDC/DDC protocol Setup. Working knowledge on ISO / API Interfaces. Experience on Terminal driving certifications like ADVT and MTIP. Should have Working experience Linux and MySQL / MariaDB. Batch Scripting will have added advantage

In [10]:
print(
    jobs["tags_and_skills"]
    .dropna()
    .head(20)
    .to_string(index=False)
)

Communication,Manpower,Staffing,Convincing Powe...
Safety Officer Activities,Fire Protection,Fire ...
Performance Marketing,User Acquisition,growth m...
Fluent English,Spoken English,Good English Comm...
Product Marketing,CNS,Product Management,Nephro...
Tds Filing,ITR,Gst Filing,Balance Sheet Finalis...
Booth,Conveyor,Special Process,Utility Maintena...
M.S Office,SAP,Computer Skills,MS Office,Techni...
  SAP,Laboratory Knowledge,Microsoft,Technical,Lab
Sre,Azure Devops,Monitoring Tools,Site,Site Rel...
BPO,Domestic Voice Process,Non Voice Process,Do...
Blue Collar Hiring,Talent Acquisition,Recruitme...
Chat Support,US Process,Customer Support,Custom...
                Bakery,shift,Assistance,Management
NBFC,Bulk Hiring,Sales Hiring,Non IT Recruitmen...
Mep Billing Engineer,Mep Billing,Site Billing,M...
Compliance Monitoring,Credit Card Fraud,Fraud M...
Fiber Optics,Ftth,Fttx,NLD,Deployment,Tower Ere...
Mechanical,Billing,Planning,Billing Engineering...
Tekla,AutoCAD,Mechanical Design,Solid Works,Boc...

In [11]:
from collections import Counter

skill_counter = Counter()

for value in jobs["tags_and_skills"].dropna():

    skills_in_job = str(value).split(",")

    for skill in skills_in_job:
        skill = skill.strip()

        if skill:
            skill_counter[skill.lower()] += 1

print("Unique raw skills:", len(skill_counter))

skill_frequency = pd.DataFrame(
    skill_counter.items(),
    columns=["skill", "job_count"]
).sort_values(
    "job_count",
    ascending=False
)

skill_frequency.head(100)

Unique raw skills: 44078

                       skill  job_count
103                    sales       9206
476                   python       5846
233       project management       5543
91          customer service       5122
57                       sap       5043
...                      ...        ...
294               healthcare        915
1045      performance tuning        889
271   stakeholder management        888
131                   senior        886
354                      gcp        886

[100 rows x 2 columns]

In [12]:
thresholds = [5, 10, 25, 50, 100, 250, 500, 1000]

for threshold in thresholds:
    count = (skill_frequency["job_count"] >= threshold).sum()
    print(f"{threshold:>4} jobs: {count:>5} skills")

   5 jobs: 11230 skills
  10 jobs:  7544 skills
  25 jobs:  4159 skills
  50 jobs:  2444 skills
 100 jobs:  1329 skills
 250 jobs:   531 skills
 500 jobs:   232 skills
1000 jobs:    83 skills

In [13]:
candidate_skills = skill_frequency[
    skill_frequency["job_count"] >= 250
].copy()

print("Candidate skills:", len(candidate_skills))

candidate_skills

Candidate skills: 531

                   skill  job_count
103                sales       9206
476               python       5846
233   project management       5543
91      customer service       5122
57                   sap       5043
...                  ...        ...
101   non it recruitment        252
1125            payments        252
337      cloud computing        252
783      territory sales        250
974    leadership skills        250

[531 rows x 2 columns]

In [14]:
noise_words = {
    "senior",
    "junior",
    "good",
    "knowledge",
    "experience",
    "required",
    "skills",
    "skill",
    "job",
    "jobs",
    "work",
    "working",
    "hiring",
    "recruitment",
    "recruiting",
    "candidate",
    "candidates",
    "management",
    "manager",
    "professional",
    "team",
    "communication",
    "responsibilities",
    "qualification",
    "qualifications",
    "fresher",
    "fresher's",
    "years",
    "year"
}

candidate_skills["is_noise"] = (
    candidate_skills["skill"]
    .str.lower()
    .isin(noise_words)
)

print(
    candidate_skills[
        candidate_skills["is_noise"]
    ]
)

           skill  job_count  is_noise
88    management       4849      True
5    recruitment       1797      True
4         hiring        935      True
131       senior        886      True
877         team        323      True
975      fresher        296      True

In [15]:
filtered_candidates = candidate_skills[
    ~candidate_skills["is_noise"]
].copy()

print(
    "Candidates after first filter:",
    len(filtered_candidates)
)

Candidates after first filter: 525

In [16]:
# Remove very short / obviously non-skill entries
filtered_candidates = filtered_candidates[
    filtered_candidates["skill"].str.len() >= 2
].copy()

# Remove entries that are purely numeric
filtered_candidates = filtered_candidates[
    ~filtered_candidates["skill"].str.fullmatch(r"\d+")
].copy()

print("Candidates:", len(filtered_candidates))

Candidates: 524

In [17]:
filtered_candidates.sort_values(
    "job_count"
).head(100)

                       skill  job_count  is_noise
974        leadership skills        250     False
783          territory sales        250     False
337          cloud computing        252     False
1125                payments        252     False
101       non it recruitment        252     False
...                      ...        ...       ...
53    preventive maintenance        293     False
719              back office        293     False
3455                      cd        293     False
2418       analytical skills        295     False
1791    portfolio management        295     False

[100 rows x 3 columns]

In [18]:
pd.set_option("display.max_rows", 600)

filtered_candidates[
    ["skill", "job_count"]
].sort_values(
    "job_count",
    ascending=False
)

                                    skill  job_count
103                                 sales       9206
476                                python       5846
233                    project management       5543
91                       customer service       5122
57                                    sap       5043
358                                   css       4188
382                                  java       4088
380                                   sql       3983
201                  business development       3745
7                    communication skills       3499
641                           development       3311
339                            javascript       3006
1207                                   c#       2978
23                              marketing       2503
414                       troubleshooting       2470
1093                                agile       2459
1102                           accounting       2435
31                                english       2272
401                            automation       2269
250                       team management       2268
219                            analytical       2159
1603                               oracle       2135
289                            networking       2085
1331                                 rest       2054
242                            operations       2043
319                      software testing       1993
379                                   c++       1987
1312                                  aws       1884
254                         data analysis       1870
440                              training       1850
999                         voice process       1845
90                       customer support       1828
303                       lead generation       1800
75                                    bpo       1768
854                continuous integration       1751
610                            consulting       1729
633                                  html       1600
481                  software development       1579
1094              application development       1574
629                         microservices       1544
523                             b2b sales       1536
570                            kubernetes       1509
628                           spring boot       1499
3946                         web services       1468
754                               finance       1460
1139                                  erp       1453
199                         channel sales       1398
376                                 excel       1312
631                              react.js       1289
644                           field sales       1256
487                         team handling       1251
1089                     computer science       1206
133                               autocad       1188
904           international voice process       1187
1230                    digital marketing       1186
182                                 linux       1176
313                            compliance       1174
546                      machine learning       1163
74                        microsoft azure       1153
334                     business analysis       1148
282                             debugging       1144
2397                      risk management       1136
531                        administration       1128
839                                 hindi       1124
388                         documentation       1120
798                            production       1111
408                          relationship       1089
579                      accounts payable       1075
1360                          procurement       1075
211                             telesales       1065
2241                   automation testing       1065
1034                  presentation skills       1057
569                                 ci/cd       1049
1692                                  git       1048
4227                            hibernate       1038
321                                coding       1035
856                                  data       1025
148                     international bpo       1020
1747             hr generalist activities       1014
73                                 devops       1007
225               relationship management       1005
1019                            screening        996
1514                      market research        970
1044                        data modeling        964
480               artificial intelligence        961
1782                  accounts receivable        953
261                       data management        945
370                          cold calling        941
1005                              angular        939
1251                        customer care        933
1109                         supply chain        933
130                           engineering        917
294                            healthcare        915
1045                   performance tuning        889
271                stakeholder management        888
354                                   gcp        886
1006                               spring        886
84                     talent acquisition        870
568                                 cloud        868
406                  interpersonal skills        866
1029                             power bi        866
955                               process        856
547                          inside sales        851
92              international call center        849
1407                             sap hana        847
671                      sales management        842
544                              teaching        830
237                          architecture        830
5322                   financial analysis        826
5430                   application design        825
348                               banking        824
784                          direct sales        822
176                                   tds        816
514                                design        815
844                     technical support        812
1961                                 .net        807
993                             b2c sales        802
1033                operations management        798
2243                                  etl        792
927                       content writing        790
478                                   api        779
17983           development methodologies        776
1654                  sales and marketing        769
1020                                 hrsd        758
77                      non voice process        753
566                                docker        743
389                              auditing        741
2266                  root cause analysis        739
3665                             selenium        734
59                              ms office        721
1477                      insurance sales        721
29                                billing        715
209                           telecalling        714
2664                  joining formalities        713
415                     change management        710
1816                                  gst        708
827                        life insurance        706
224                            monitoring        706
216                               calling        704
241                              research        699
3719                              backend        699
1194                      quality control        695
1252                                voice        692
1268                    quality assurance        690
336                                   mis        686
3418                           full stack        677
3677                                 hive        676
614                                  dbms        672
1876                          negotiation        667
1215                customer relationship        667
1096                         social media        662
302                                retail        659
470                                   b2b        656
3395                       data analytics        655
429                           forecasting        650
87                               sourcing        650
202                          retail sales        650
709                     vendor management        650
372                       corporate sales        647
1456                            analytics        646
1330                    design principles        645
1404                             sap abap        643
366                    program management        641
3969                     data warehousing        640
1092                           postgresql        638
185                                 mysql        638
196                             insurance        634
308                    financial services        632
5173      software development life cycle        622
3421                           salesforce        622
34                     product management        618
3                        convincing power        617
1025                           algorithms        617
238                    manager technology        617
479                              software        605
220                   process improvement        605
3830                              pyspark        604
1180                            budgeting        596
1222                          hospitality        594
160                       blended process        593
97                             assistance        587
1247                              project        585
89                             us process        584
3968                                scala        584
283                                  jira        584
222                continuous improvement        583
3022                             taxation        580
3778                                  jsp        580
1302                                  crm        579
5175                               jquery        577
817                               payroll        575
3010                           test cases        574
621                    client acquisition        574
931                                   seo        569
1690                        voice support        569
571                            leadership        568
2909                 technical leadership        563
536                             photoshop        558
3009                       manual testing        553
517                              analysis        553
263                                 scrum        552
60                              technical        551
3034                      version control        551
1048                               github        545
5866                   service operations        543
1491                      problem solving        542
945            sales executive activities        541
490                              handling        537
802                       inbound process        537
1290                            bpo voice        536
1156                  international voice        534
1897                       it recruitment        533
65                              microsoft        532
299                 relationship building        532
22                                  usage        529
1214                                tally        529
691                             logistics        519
2222                           servicenow        517
2839                              node.js        515
127                              planning        513
205                         us healthcare        513
375                              purchase        513
3017                            front end        510
329                  inventory management        507
306                 customer satisfaction        506
4286                           sap s hana        506
20                            acquisition        503
770                           maintenance        501
1208                            .net core        498
660                        reconciliation        496
668        client relationship management        488
1274                         distribution        487
1359               information technology        483
1689                     data engineering        483
472                         cross selling        480
1635                               sap sd        480
262                   financial reporting        479
63                                 office        478
853                            generation        467
1022          natural language processing        466
4766                            bootstrap        464
1358                         unit testing        463
1536                 bpo customer service        463
298                        branch banking        459
1661                   target achievement        458
371       business development management        458
1605                          it services        456
116                       risk assessment        454
2356                         coordination        451
3269                    agile methodology        451
3008                   regression testing        451
699                             corporate        449
149                   international sales        449
830                             reporting        447
1582                           typescript        445
520                                   iso        444
1479                       agency channel        443
24                         fluent english        443
2429                        balance sheet        439
1003                            snowflake        439
646                    revenue generation        437
3065                      content editing        436
597                            home loans        435
565                               jenkins        435
2570               end to end recruitment        433
218             manager quality assurance        433
443                                    hr        432
221                            scheduling        431
3062                           sql server        430
1598                        hr operations        430
1027                                plsql        430
1248                                field        423
550                               inbound        423
2128                   investment banking        422
933                    content management        419
1200                              quality        418
163                          chat process        417
1356               performance management        415
2819                                 unix        415
1209                                azure        411
638                        pharmaceutical        410
1250                        inbound calls        407
2463                                spark        406
2701                                  cms        405
1342                              android        401
912                        cyber security        399
3036                      data structures        397
7635                            assurance        396
926                               tableau        396
835                                 kafka        395
297                                 loans        395
3553                      stress analysis        394
1728                       outbound sales        390
4304                  performance testing        389
2008                            tally erp        389
2254                  employee engagement        388
2405                             outbound        387
266                 business intelligence        387
1570               mechanical engineering        387
3357                             presales        387
235                                   cad        386
3059                             sap fico        385
1783                      journal entries        384
362                             wordpress        384
1219                    customer handling        383
1405                                 abap        383
463                                sap mm        382
1303                          electricals        382
1846            human resource management        382
1362                  incident management        381
997                         international        380
765                electrical engineering        378
746                        advanced excel        373
423                        sales strategy        371
3963                     web technologies        369
21370                          moderation        369
1914                    management skills        369
27                                medical        368
1842                          counselling        368
1137                       medical coding        367
1941                 sap abap development        366
2386                      time management        366
2074                                  dns        366
3069                                focus        365
1249                inbound voice process        365
2515                          real estate        363
723                            front desk        360
1261                        business loan        360
198                      health insurance        360
214                      outbound calling        360
3972                            switching        358
994                    account management        357
534                           illustrator        357
332                operational excellence        357
831                    financial planning        356
80                           chat support        356
2762                     creative writing        355
1007                                 boot        355
2208                        sales process        353
567                             terraform        351
1072                                  xml        351
1659                           bfsi sales        350
2                                staffing        348
1009                         data science        346
328                             packaging        344
126                            mechanical        344
1040                              editing        344
1595                   employee relations        343
1138                             workflow        343
2530                 verbal communication        343
5473                  database management        342
1779                  bank reconciliation        342
815                          construction        341
1106                               hadoop        341
215                           collections        339
1254                          cross sales        338
620                new client acquisition        338
1369                        video editing        338
1954                    real estate sales        334
4320                                 fico        333
1032                                   bi        332
1151                              control        332
537                     graphic designing        331
2884                 architectural design        331
273                          data quality        331
1155   excellent communication in english        330
138                           fabrication        329
758                             education        328
592                 loan against property        328
884                  statutory compliance        328
1388                     us voice process        327
150                             upselling        326
279                                 legal        326
782                               general        324
2376                         front office        324
2291                 information security        324

In [19]:
filtered_candidates[
    ["skill", "job_count"]
].to_csv(
    "../data/skill_candidates.csv",
    index=False
)

print("Saved:", len(filtered_candidates), "candidate skills")

Saved: 524 candidate skills

In [20]:
final_skills = (
    filtered_candidates["skill"]
    .str.strip()
    .drop_duplicates()
    .tolist()
)

print("Final taxonomy size:", len(final_skills))

Final taxonomy size: 524

In [21]:
from bs4 import BeautifulSoup

def clean_html(text):
    if pd.isna(text):
        return ""

    return BeautifulSoup(
        str(text),
        "html.parser"
    ).get_text(" ", strip=True)

In [22]:
text = clean_html(jobs.loc[27, "job_description"])

print(text[:2000])

Experience : 4 - 8 Years of relevant experience working in the skillset Skillset: Hands on experience on ATM/CRM/BNA System. Should have knowledge on ATM terminals of NCR / Wincor / Okie / Hitachi makes Extensive experience on XFS layer. Understanding of client  server model. Should have experience on Screen Design, Screen Flow, States, etc Should have working experience on NDC/DDC Protocol. Should have working experience with NDC/DDC protocol Setup. Working knowledge on ISO / API Interfaces. Experience on Terminal driving certifications like ADVT and MTIP. Should have Working experience Linux and MySQL / MariaDB. Batch Scripting will have added advantage

In [23]:
doc = nlp(text)

matches = matcher(doc)

found_skills = sorted(
    set(
        doc[start:end].text.strip()
        for _, start, end in matches
    ),
    key=str.lower
)

print("Job title:", jobs.loc[27, "title"])
print("\nExtracted skills:")
print(found_skills)

Job title: ATM Implementation - Software Engineer / Senior Software Engineer

Extracted skills:
['Linux', 'MySQL']

In [24]:
def extract_skills_from_doc(doc):
    matches = matcher(doc)

    found = set()

    for _, start, end in matches:
        skill = doc[start:end].text.strip()

        if skill:
            found.add(skill)

    return sorted(found, key=str.lower)

In [25]:
descriptions = jobs["job_description"].fillna("").map(clean_html).tolist()

all_extracted_skills = []

for i, doc in enumerate(nlp.pipe(descriptions, batch_size=1000)):

    all_extracted_skills.append(
        extract_skills_from_doc(doc)
    )

    if (i + 1) % 10000 == 0:
        print(f"Processed {i + 1:,} / {len(descriptions):,}")

C:\Users\gouda\AppData\Local\Temp\ipykernel_11936\3950033103.py:7: MarkupResemblesLocatorWarning: The input passed in on this line looks more like a URL than HTML or XML.

If you meant to use Beautiful Soup to parse the web page found at a certain URL, then something has gone wrong. You should use an Python package like 'requests' to fetch the content behind the URL. Once you have the content as a string, you can feed that string into Beautiful Soup.

However, if you want to parse some data that happens to look like a URL, then nothing has gone wrong: you are using Beautiful Soup correctly, and this warning is spurious and can be filtered. To make this warning go away, run this code before calling the BeautifulSoup constructor:

    from bs4 import MarkupResemblesLocatorWarning
    import warnings

    warnings.filterwarnings("ignore", category=MarkupResemblesLocatorWarning)

  return BeautifulSoup(

Processed 10,000 / 97,679
Processed 20,000 / 97,679
Processed 30,000 / 97,679
Processed 40,000 / 97,679
Processed 50,000 / 97,679
Processed 60,000 / 97,679
Processed 70,000 / 97,679
Processed 80,000 / 97,679
Processed 90,000 / 97,679

In [26]:
jobs["extracted_skills"] = all_extracted_skills

print("Extraction complete.")

Extraction complete.

In [27]:
jobs[
    ["title", "extracted_skills"]
].head(20)

                                                title extracted_skills
0                           Sr. HR Recruiter (NON IT)               []
1                             Fire And Safety Officer               []
2         Opening For Performance Marketing - Chennai               []
3                           Medical Billing Executive               []
4         Senior Group Product Manager -  CNS Therapy               []
5                                   Senior Accountant               []
6                              Maintenance Technician               []
7                          Officer/Engineer Technical               []
8                              Officer- Technical Lab               []
9                           Site Reliability Engineer         [Python]
10                    Hiring For Voice & Chat Process               []
11                    Talent Acquisition Professional               []
12                            Hiring For Chat Process               []
13                          Assistant Manager- Bakery               []
14         HR Recruiter | Regional Recruiter | Jaipur               []
15                      MEP Billing Engineer (Jaipur)               []
16  JOB For MALE |Fraud Prevention Credit card || ...               []
17                Pole Deployment Engineer (Off Role)               []
18  Senior Engineer-Mechanical (Planning/Billing),...               []
19  Design Engineer-Mechanical/Civil (Fabrication ...               []

In [28]:
jobs_with_skills = jobs["extracted_skills"].str.len().gt(0)

print(
    "Jobs with at least one extracted skill:",
    jobs_with_skills.sum()
)

print(
    "Skill extraction coverage:",
    round(
        jobs_with_skills.mean() * 100,
        2
    ),
    "%"
)

Jobs with at least one extracted skill: 33873
Skill extraction coverage: 34.68 %

In [29]:
from collections import Counter

extracted_counter = Counter()

for skill_list in jobs["extracted_skills"]:
    extracted_counter.update(skill_list)

extracted_frequency = pd.DataFrame(
    extracted_counter.items(),
    columns=["skill", "job_count"]
).sort_values(
    "job_count",
    ascending=False
)

extracted_frequency.head(50)

                    skill  job_count
8                     SAP       5606
12                    SQL       4164
0                  Python       3517
48                   Java       3479
15                  Azure       3397
1                     AWS       3282
2                   Excel       2822
35                  Agile       2653
62                 Oracle       1947
33               research       1842
14   software development       1685
49             JavaScript       1612
81           optimization       1596
19                    GCP       1483
92                  CI/CD       1430
42             Kubernetes       1398
54                 Spring       1379
58                      C       1376
47                    Git       1330
51                  React       1256
27                 Docker       1221
82                Angular       1209
4                   Linux       1168
130                 agile       1163
94                  Scrum       1153
21                Jenkins       1096
71                    ETL       1058
34             networking       1003
103         microservices        987
73                    CSS        987
45             Salesforce        956
55            Spring Boot        873
74                   HTML        871
161                GitHub        808
41                  Kafka        764
169                    C#        710
170               CI / CD        696
3                Research        690
5                   MySQL        689
31               Power BI        684
106            PostgreSQL        646
79             SQL Server        645
105         Microservices        644
61             ServiceNow        635
218  Software Development        586
80              Terraform        572
182              SAP ABAP        567
97                  excel        561
109              Selenium        555
22                   JIRA        555

In [30]:
print("Unique extracted skills:", len(extracted_frequency))

Unique extracted skills: 670

In [31]:
extracted_frequency.head(50)

                    skill  job_count
8                     SAP       5606
12                    SQL       4164
0                  Python       3517
48                   Java       3479
15                  Azure       3397
1                     AWS       3282
2                   Excel       2822
35                  Agile       2653
62                 Oracle       1947
33               research       1842
14   software development       1685
49             JavaScript       1612
81           optimization       1596
19                    GCP       1483
92                  CI/CD       1430
42             Kubernetes       1398
54                 Spring       1379
58                      C       1376
47                    Git       1330
51                  React       1256
27                 Docker       1221
82                Angular       1209
4                   Linux       1168
130                 agile       1163
94                  Scrum       1153
21                Jenkins       1096
71                    ETL       1058
34             networking       1003
103         microservices        987
73                    CSS        987
45             Salesforce        956
55            Spring Boot        873
74                   HTML        871
161                GitHub        808
41                  Kafka        764
169                    C#        710
170               CI / CD        696
3                Research        690
5                   MySQL        689
31               Power BI        684
106            PostgreSQL        646
79             SQL Server        645
105         Microservices        644
61             ServiceNow        635
218  Software Development        586
80              Terraform        572
182              SAP ABAP        567
97                  excel        561
109              Selenium        555
22                   JIRA        555

In [32]:
print(extracted_frequency["job_count"].describe())

count     670.000000
mean      169.143284
std       477.514664
min         1.000000
25%         3.000000
50%        15.000000
75%       115.750000
max      5606.000000
Name: job_count, dtype: float64

In [33]:
def canonicalize_skill(skill):
    s = str(skill).strip().lower()

    aliases = {
        "agile": "Agile",
        "research": "Research",
        "ci / cd": "CI/CD",
        "ci/cd": "CI/CD",
        "excel": "Excel",
        "microservices": "Microservices",
        "software development": "Software Development",
        "java script": "JavaScript",
        "power bi": "Power BI",
        "jira": "Jira",
        "gcp": "GCP",
        "aws": "AWS",
        "azure": "Azure",
        "postgres": "PostgreSQL",
        "sql server": "SQL Server",
        "kafka": "Kafka",
        "apache kafka": "Kafka"
    }

    return aliases.get(s, str(skill).strip())

In [34]:
jobs["extracted_skills"] = jobs["extracted_skills"].apply(
    lambda skills: sorted(
        set(canonicalize_skill(skill) for skill in skills),
        key=str.lower
    )
)

In [35]:
extracted_counter = Counter()

for skill_list in jobs["extracted_skills"]:
    extracted_counter.update(skill_list)

extracted_frequency = pd.DataFrame(
    extracted_counter.items(),
    columns=["skill", "job_count"]
).sort_values(
    "job_count",
    ascending=False
)

print("Unique canonical skills:", len(extracted_frequency))

extracted_frequency.head(50)

Unique canonical skills: 627

                    skill  job_count
8                     SAP       5606
12                    SQL       4164
34                  Agile       3641
0                  Python       3517
47                   Java       3479
15                  Azure       3422
2                   Excel       3343
1                     AWS       3297
3                Research       2335
14   Software Development       2242
91                  CI/CD       2128
61                 Oracle       1947
48             JavaScript       1612
80           optimization       1596
101         Microservices       1555
19                    GCP       1483
41             Kubernetes       1398
53                 Spring       1379
57                      C       1376
46                    Git       1330
50                  React       1256
27                 Docker       1221
81                Angular       1209
4                   Linux       1168
93                  Scrum       1153
21                Jenkins       1096
22                   Jira       1093
70                    ETL       1058
33             networking       1003
72                    CSS        987
44             Salesforce        956
54            Spring Boot        873
73                   HTML        871
157                GitHub        808
40                  Kafka        783
31               Power BI        713
164                    C#        710
78             SQL Server        694
5                   MySQL        689
103            PostgreSQL        646
60             ServiceNow        635
79              Terraform        572
176              SAP ABAP        567
106              Selenium        555
13                     go        552
49                MongoDB        549
68       data engineering        535
71              Snowflake        505
35                Ansible        499
18   software engineering        498

In [36]:
display_names = {
    "go": "Go",
    "optimization": "Optimization",
    "networking": "Networking",
    "data engineering": "Data Engineering",
    "software engineering": "Software Engineering"
}

jobs["extracted_skills"] = jobs["extracted_skills"].apply(
    lambda skill_list: sorted(
        {
            display_names.get(
                skill.lower(),
                skill
            )
            for skill in skill_list
        },
        key=str.lower
    )
)

In [37]:
extracted_counter = Counter()

for skill_list in jobs["extracted_skills"]:
    extracted_counter.update(skill_list)

extracted_frequency = pd.DataFrame(
    extracted_counter.items(),
    columns=["skill", "job_count"]
).sort_values(
    "job_count",
    ascending=False
)

print("Final extracted skill count:", len(extracted_frequency))

extracted_frequency.head(30)

Final extracted skill count: 618

                   skill  job_count
8                    SAP       5606
12                   SQL       4164
34                 Agile       3641
0                 Python       3517
46                  Java       3479
15                 Azure       3422
2                  Excel       3343
1                    AWS       3297
3               Research       2335
14  Software Development       2242
88                 CI/CD       2128
58                Oracle       1947
77          Optimization       1881
47            JavaScript       1612
97         Microservices       1555
19                   GCP       1483
41            Kubernetes       1398
51                Spring       1379
54                     C       1376
45                   Git       1330
33            Networking       1267
49                 React       1256
27                Docker       1221
78               Angular       1209
4                  Linux       1168
90                 Scrum       1153
21               Jenkins       1096
22                  Jira       1093
67                   ETL       1058
69                   CSS        987

In [38]:
skills_df = pd.DataFrame({
    "skill_name": extracted_frequency["skill"].tolist()
})

skills_df.insert(
    0,
    "skill_id",
    range(1, len(skills_df) + 1)
)

print("Skills:", len(skills_df))
skills_df.head(20)

Skills: 618

    skill_id            skill_name
0          1                   SAP
1          2                   SQL
2          3                 Agile
3          4                Python
4          5                  Java
5          6                 Azure
6          7                 Excel
7          8                   AWS
8          9              Research
9         10  Software Development
10        11                 CI/CD
11        12                Oracle
12        13          Optimization
13        14            JavaScript
14        15         Microservices
15        16                   GCP
16        17            Kubernetes
17        18                Spring
18        19                     C
19        20                   Git

In [39]:
skills_df.to_sql(
    "skills",
    engine,
    if_exists="replace",
    index=False
)

print("✅ skills table created")

✅ skills table created

In [40]:
job_skill_rows = []

for _, row in jobs[
    ["job_id", "extracted_skills"]
].iterrows():

    for skill in row["extracted_skills"]:

        job_skill_rows.append({
            "job_id": row["job_id"],
            "skill_name": skill
        })

job_skills_df = pd.DataFrame(job_skill_rows)

print("Raw relationships:", len(job_skills_df))

Raw relationships: 112130

In [41]:
job_skills_df = job_skills_df.merge(
    skills_df,
    on="skill_name",
    how="inner"
)

In [42]:
job_skills_df = job_skills_df[
    ["job_id", "skill_id"]
].drop_duplicates()

print(
    "Unique job-skill relationships:",
    len(job_skills_df)
)

Unique job-skill relationships: 112130

In [43]:
job_skills_df.to_sql(
    "job_skills",
    engine,
    if_exists="replace",
    index=False,
    chunksize=10000,
    method="multi"
)

print("✅ job_skills table created")

✅ job_skills table created

In [44]:
query = """
SELECT
    COUNT(*) AS relationships
FROM job_skills;
"""

pd.read_sql(query, engine)

   relationships
0         112130

In [45]:
query = """
SELECT
    COUNT(*) AS total_skills
FROM skills;
"""

pd.read_sql(query, engine)

   total_skills
0           618

In [46]:
query = """
SELECT
    s.skill_name,
    COUNT(js.job_id) AS job_count
FROM job_skills js
JOIN skills s
    ON js.skill_id = s.skill_id
GROUP BY s.skill_name
ORDER BY job_count DESC
LIMIT 20;
"""

pd.read_sql(query, engine)

              skill_name  job_count
0                    SAP       5606
1                    SQL       4164
2                  Agile       3641
3                 Python       3517
4                   Java       3479
5                  Azure       3422
6                  Excel       3343
7                    AWS       3297
8               Research       2335
9   Software Development       2242
10                 CI/CD       2128
11                Oracle       1947
12          Optimization       1881
13            JavaScript       1612
14         Microservices       1555
15                   GCP       1483
16            Kubernetes       1398
17                Spring       1379
18                     C       1376
19                   Git       1330

In [50]:
from sqlalchemy import text

pd.read_sql("""
    SELECT
        COUNT(*) AS total_rows,
        COUNT(DISTINCT job_id) AS unique_job_ids
    FROM jobs;
""", engine)

   total_rows  unique_job_ids
0       97679           97679

In [53]:
from sqlalchemy import text

with engine.begin() as conn:
    conn.execute(text("""
        ALTER TABLE skills
        ADD CONSTRAINT skills_pk
        PRIMARY KEY (skill_id);
    """))

print("✅ skills.skill_id is now the primary key")

✅ skills.skill_id is now the primary key

In [54]:
with engine.begin() as conn:
    conn.execute(text("""
        ALTER TABLE job_skills
        ADD CONSTRAINT job_skills_skill_fk
        FOREIGN KEY (skill_id)
        REFERENCES skills(skill_id);
    """))

print("✅ skills foreign key added")

✅ skills foreign key added

In [55]:
pd.read_sql("""
    SELECT
        COUNT(*) AS relationships
    FROM job_skills js
    JOIN jobs j
        ON js.job_id = j.job_id
    JOIN skills s
        ON js.skill_id = s.skill_id;
""", engine)

   relationships
0         112130